# Generated by Django 4.2.2 on 2023-06-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentacar', '0002_car_reservation_reservation_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
